/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bsiemon' at '10/26/16 12:06 PM' with Gradle 3.1
 *
 * @author bsiemon, @date 10/26/16 12:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
